spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/authorization?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        username: root
        password: root
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect



